SESSION_MAX_SESSIONS_PER_USER: 2

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lms?useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secretKey: ${JWT_SECRET}
  expiration: 86400
  refreshExpiration: 60480